// frontend/src/App.tsx
import { useEffect, useMemo, useState } from 'react';
import { api } from './api';
import type { Bill, Category, Insight, Product } from './models';
import './styles.css';

type CartLine = { product: Product; qty: number };

const defaultForm = { name: '', categoryId: 0, price: 0, defaultDiscount: 0 };

export default function App() {
  const [products, setProducts] = useState<Product[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [topProducts, setTopProducts] = useState<Insight[]>([]);
  const [topCategories, setTopCategories] = useState<Insight[]>([]);
  const [bills, setBills] = useState<Bill[]>([]);
  const [cart, setCart] = useState<CartLine[]>([]);

  const [search, setSearch] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<number | ''>('');
  const [gstPercent, setGstPercent] = useState(0);
  const [discountAmount, setDiscountAmount] = useState(0);

  const [editingProductId, setEditingProductId] = useState<number | null>(null);
  const [form, setForm] = useState(defaultForm);
  const [error, setError] = useState('');

  const loadAll = async () => {
    try {
      const [p, c, tp, tc, b] = await Promise.all([
        api.products(),
        api.categories(),
        api.topProducts(),
        api.topCategories(),
        api.bills()
      ]);
      setProducts(p);
      setCategories(c);
      setTopProducts(tp);
      setTopCategories(tc);
      setBills(b);
      setError('');
    } catch {
      setError('Failed to load data. Ensure backend is running on http://localhost:5000.');
    }
  };

  useEffect(() => {
    loadAll();
  }, []);

  const filteredProducts = useMemo(
    () =>
      products.filter(
        (p) =>
          (!selectedCategory || p.categoryId === selectedCategory) &&
          p.name.toLowerCase().includes(search.toLowerCase())
      ),
    [products, selectedCategory, search]
  );

  const subTotal = useMemo(() => cart.reduce((sum, c) => sum + c.product.price * c.qty, 0), [cart]);
  const taxAmount = useMemo(() => Math.max(0, subTotal - discountAmount) * (gstPercent / 100), [subTotal, discountAmount, gstPercent]);
  const finalAmount = useMemo(() => Math.max(0, subTotal - discountAmount) + taxAmount, [subTotal, discountAmount, taxAmount]);

  const saveProduct = async () => {
    const payload = { ...form, isActive: true };
    if (!payload.name || !payload.categoryId || payload.price <= 0) return;

    if (editingProductId) {
      await api.updateProduct(editingProductId, payload);
    } else {
      await api.createProduct(payload);
    }

    setForm(defaultForm);
    setEditingProductId(null);
    await loadAll();
  };

  const addToCart = (product: Product) => {
    setCart((prev) => {
      const line = prev.find((c) => c.product.id === product.id);
      if (line) return prev.map((c) => (c.product.id === product.id ? { ...c, qty: c.qty + 1 } : c));
      return [...prev, { product, qty: 1 }];
    });
  };

  const changeQty = (productId: number, delta: number) => {
    setCart((prev) =>
      prev
        .map((c) => (c.product.id === productId ? { ...c, qty: c.qty + delta } : c))
        .filter((c) => c.qty > 0)
    );
  };

  const generateBill = async () => {
    if (!cart.length) return;
    await api.createBill({
      discountAmount,
      gstPercent,
      items: cart.map((c) => ({ productId: c.product.id, quantity: c.qty }))
    });
    setCart([]);
    setDiscountAmount(0);
    setGstPercent(0);
    await loadAll();
  };

  return (
    <div className="page">
      <h1>Smart Kaccha Bill (React)</h1>
      {error && <p className="error">{error}</p>}

      <section>
        <h2>Insights</h2>
        <p>Top products: {topProducts.map((t) => `${t.name} (${t.value})`).join(', ') || '—'}</p>
        <p>Top categories: {topCategories.map((t) => `${t.name} (₹${t.value.toFixed(0)})`).join(', ') || '—'}</p>
      </section>

      <section>
        <h2>Product Setup</h2>
        <div className="row">
          <input value={form.name} onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))} placeholder="Product" />
          <select value={form.categoryId} onChange={(e) => setForm((f) => ({ ...f, categoryId: Number(e.target.value) }))}>
            <option value={0}>Category</option>
            {categories.map((c) => (
              <option key={c.id} value={c.id}>{c.name}</option>
            ))}
          </select>
          <input type="number" value={form.price} onChange={(e) => setForm((f) => ({ ...f, price: Number(e.target.value) }))} placeholder="Price" />
          <button onClick={saveProduct}>{editingProductId ? 'Update' : 'Add'}</button>
        </div>

        <ul>
          {products.map((p) => (
            <li key={p.id}>
              {p.name} ({p.categoryName}) ₹{p.price}
              <button onClick={() => { setEditingProductId(p.id); setForm({ name: p.name, categoryId: p.categoryId, price: p.price, defaultDiscount: p.defaultDiscount ?? 0 }); }}>Edit</button>
              <button onClick={async () => { await api.deleteProduct(p.id); await loadAll(); }}>Delete</button>
              <button onClick={() => addToCart(p)}>Add to cart</button>
            </li>
          ))}
        </ul>
      </section>

      <section>
        <h2>Billing</h2>
        <div className="row">
          <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search" />
          <select value={selectedCategory} onChange={(e) => setSelectedCategory(e.target.value ? Number(e.target.value) : '')}>
            <option value="">All categories</option>
            {categories.map((c) => (<option key={c.id} value={c.id}>{c.name}</option>))}
          </select>
        </div>
        <div className="chips">
          {filteredProducts.map((p) => (
            <button key={p.id} onClick={() => addToCart(p)}>{p.name} - ₹{p.price}</button>
          ))}
        </div>

        {cart.map((line) => (
          <div key={line.product.id} className="row">
            <span>{line.product.name}</span>
            <div>
              <button onClick={() => changeQty(line.product.id, -1)}>-</button>
              <span>{line.qty}</span>
              <button onClick={() => changeQty(line.product.id, 1)}>+</button>
            </div>
          </div>
        ))}

        <div className="row">
          <label>Discount <input type="number" value={discountAmount} onChange={(e) => setDiscountAmount(Number(e.target.value))} /></label>
          <label>GST
            <select value={gstPercent} onChange={(e) => setGstPercent(Number(e.target.value))}>
              {[0, 5, 12, 18, 28].map((v) => <option key={v} value={v}>{v}%</option>)}
            </select>
          </label>
        </div>

        <p>Subtotal: ₹{subTotal.toFixed(2)}</p>
        <p>Tax: ₹{taxAmount.toFixed(2)}</p>
        <p>Total: ₹{finalAmount.toFixed(2)}</p>
        <button onClick={generateBill}>Generate Bill</button>
      </section>

      <section>
        <h2>Latest Bill</h2>
        {bills[0] ? (
          <div>
            <p>{bills[0].invoiceNumber} | {new Date(bills[0].createdAt).toLocaleString()}</p>
            <ul>
              {bills[0].items.map((i) => (<li key={i.id}>{i.productName} x{i.quantity} = ₹{i.total}</li>))}
            </ul>
            <strong>Final: ₹{bills[0].finalAmount.toFixed(2)}</strong>
          </div>
        ) : <p>No bills yet.</p>}
      </section>
    </div>
  );
}

// frontend/src/app/app.component.ts
import { CommonModule } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from './core/api.service';
import { Bill, Category, Insight, Product } from './models/models';

interface CartLine { product: Product; qty: number; }

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  private api = inject(ApiService);

  products = signal<Product[]>([]);
  categories = signal<Category[]>([]);
  topProducts = signal<Insight[]>([]);
  topCategories = signal<Insight[]>([]);
  cart = signal<CartLine[]>([]);
  bills = signal<Bill[]>([]);

  search = signal('');
  selectedCategory = signal<number | null>(null);
  gstPercent = signal(0);
  discountAmount = signal(0);

  editingProductId: number | null = null;
  form = { name: '', categoryId: 0, price: 0, defaultDiscount: 0 };

  filteredProducts = computed(() => this.products().filter(p =>
    (!this.selectedCategory() || p.categoryId === this.selectedCategory()) &&
    p.name.toLowerCase().includes(this.search().toLowerCase())
  ));

  subTotal = computed(() => this.cart().reduce((s, c) => s + (c.product.price * c.qty), 0));
  taxAmount = computed(() => Math.max(0, this.subTotal() - this.discountAmount()) * this.gstPercent() / 100);
  finalAmount = computed(() => Math.max(0, this.subTotal() - this.discountAmount()) + this.taxAmount());

  constructor() { this.loadAll(); }

  loadAll() {
    this.api.products().subscribe(v => this.products.set(v));
    this.api.categories().subscribe(v => this.categories.set(v));
    this.api.topProducts().subscribe(v => this.topProducts.set(v));
    this.api.topCategories().subscribe(v => this.topCategories.set(v));
    this.api.bills().subscribe(v => this.bills.set(v));
  }

  saveProduct() {
    const payload = { ...this.form, isActive: true };
    const call = this.editingProductId
      ? this.api.updateProduct(this.editingProductId, payload)
      : this.api.createProduct(payload);
    call.subscribe(() => {
      this.form = { name: '', categoryId: 0, price: 0, defaultDiscount: 0 };
      this.editingProductId = null;
      this.loadAll();
    });
  }

  editProduct(product: Product) {
    this.editingProductId = product.id;
    this.form = { name: product.name, categoryId: product.categoryId, price: product.price, defaultDiscount: product.defaultDiscount ?? 0 };
  }

  deleteProduct(id: number) { this.api.deleteProduct(id).subscribe(() => this.loadAll()); }

  addToCart(product: Product) {
    const copy = [...this.cart()];
    const line = copy.find(c => c.product.id === product.id);
    line ? line.qty++ : copy.push({ product, qty: 1 });
    this.cart.set(copy);
  }

  changeQty(productId: number, delta: number) {
    const copy = this.cart().map(c => c.product.id === productId ? { ...c, qty: c.qty + delta } : c).filter(c => c.qty > 0);
    this.cart.set(copy);
  }

  generateBill() {
    if (!this.cart().length) return;
    this.api.createBill({
      discountAmount: this.discountAmount(),
      gstPercent: this.gstPercent(),
      items: this.cart().map(c => ({ productId: c.product.id, quantity: c.qty }))
    }).subscribe(() => {
      this.cart.set([]);
      this.discountAmount.set(0);
      this.gstPercent.set(0);
      this.loadAll();
    });
  }

  printBill() { window.print(); }
}

<div class="min-h-screen bg-slate-950 text-slate-100">
  <div class="mx-auto max-w-7xl space-y-4 px-4 py-6">
    <header class="rounded-2xl border border-slate-800 bg-slate-900/80 p-5 shadow-lg">
      <h1 class="text-2xl font-bold">🧾 Smart Kaccha Bill</h1>
      <p class="mt-1 text-sm text-slate-300">Simple billing for kirana stores</p>
    </header>

    <section class="rounded-2xl border border-slate-800 bg-slate-900/80 p-5">
      <h2 class="mb-3 text-lg font-semibold">📊 Insights</h2>
      <div class="mb-2 flex flex-wrap gap-2">
        <span *ngFor="let i of topProducts()" class="rounded-full bg-indigo-600/30 px-3 py-1 text-xs">🔥 {{ i.name }} ({{ i.value }})</span>
      </div>
      <div class="flex flex-wrap gap-2">
        <span *ngFor="let i of topCategories()" class="rounded-full bg-emerald-600/30 px-3 py-1 text-xs">🏷️ {{ i.name }} (₹{{ i.value.toFixed(0) }})</span>
      </div>
    </section>

    <section class="grid gap-4 lg:grid-cols-2">
      <div class="rounded-2xl border border-slate-800 bg-slate-900/80 p-5">
        <h2 class="mb-3 text-lg font-semibold">📦 Product Setup</h2>
        <div class="mb-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
          <input [(ngModel)]="form.name" placeholder="Product" class="rounded-lg border border-slate-700 bg-slate-800 px-3 py-2" />
          <select [(ngModel)]="form.categoryId" class="rounded-lg border border-slate-700 bg-slate-800 px-3 py-2"><option [ngValue]="0">Category</option><option *ngFor="let c of categories()" [ngValue]="c.id">{{ c.name }}</option></select>
          <input [(ngModel)]="form.price" type="number" placeholder="Price" class="rounded-lg border border-slate-700 bg-slate-800 px-3 py-2" />
          <button (click)="saveProduct()" class="rounded-lg bg-indigo-600 px-3 py-2 font-medium hover:bg-indigo-500">{{ editingProductId ? 'Update' : 'Add' }}</button>
        </div>

        <div class="overflow-x-auto">
          <table class="w-full text-left text-sm">
            <tr class="border-b border-slate-700"><th class="p-2">Name</th><th class="p-2">Category</th><th class="p-2">Price</th><th class="p-2"></th></tr>
            <tr *ngFor="let p of products()" class="border-b border-slate-800">
              <td class="p-2">{{ p.name }}</td><td class="p-2">{{ p.categoryName }}</td><td class="p-2">₹{{ p.price }}</td>
              <td class="p-2"><button (click)="editProduct(p)" class="mr-2 rounded bg-amber-600 px-2 py-1 text-xs">Edit</button><button (click)="deleteProduct(p.id)" class="rounded bg-rose-600 px-2 py-1 text-xs">Delete</button></td>
            </tr>
          </table>
        </div>
      </div>

      <div class="rounded-2xl border border-slate-800 bg-slate-900/80 p-5">
        <h2 class="mb-3 text-lg font-semibold">🛒 Billing Screen</h2>
        <div class="mb-3 grid gap-2 sm:grid-cols-2">
          <input [ngModel]="search()" (ngModelChange)="search.set($event)" placeholder="Search products" class="rounded-lg border border-slate-700 bg-slate-800 px-3 py-2" />
          <select [ngModel]="selectedCategory()" (ngModelChange)="selectedCategory.set($event)" class="rounded-lg border border-slate-700 bg-slate-800 px-3 py-2">
            <option [ngValue]="null">All</option>
            <option *ngFor="let c of categories()" [ngValue]="c.id">{{ c.name }}</option>
          </select>
        </div>

        <div class="mb-4 grid max-h-64 grid-cols-2 gap-2 overflow-auto md:grid-cols-3">
          <button class="rounded-lg border border-slate-700 bg-slate-800 p-2 text-left hover:bg-slate-700" *ngFor="let p of filteredProducts()" (click)="addToCart(p)">
            <strong class="block text-sm">{{ p.name }}</strong>
            <small class="block text-xs text-slate-400">{{ p.categoryName }}</small>
            <span class="text-sm text-emerald-300">₹{{ p.price }}</span>
          </button>
        </div>

        <h3 class="mb-2 font-semibold">Current Bill</h3>
        <div *ngFor="let c of cart()" class="mb-1 flex items-center justify-between rounded bg-slate-800 px-3 py-2 text-sm">
          <span>{{ c.product.name }}</span>
          <div><button (click)="changeQty(c.product.id,-1)" class="rounded bg-slate-700 px-2">-</button> <span class="px-2">{{ c.qty }}</span> <button (click)="changeQty(c.product.id,1)" class="rounded bg-slate-700 px-2">+</button></div>
        </div>

        <div class="my-3 grid gap-2 sm:grid-cols-2">
          <label class="text-sm">Discount <input [ngModel]="discountAmount()" (ngModelChange)="discountAmount.set(+$event)" type="number" class="mt-1 w-full rounded border border-slate-700 bg-slate-800 px-3 py-2" /></label>
          <label class="text-sm">GST <select [ngModel]="gstPercent()" (ngModelChange)="gstPercent.set(+$event)" class="mt-1 w-full rounded border border-slate-700 bg-slate-800 px-3 py-2"><option *ngFor="let g of [0,5,12,18,28]" [ngValue]="g">{{g}}%</option></select></label>
        </div>

        <p class="text-sm">Subtotal: ₹{{ subTotal().toFixed(2) }}</p>
        <p class="text-sm">Tax: ₹{{ taxAmount().toFixed(2) }}</p>
        <h3 class="mb-3 text-lg font-bold text-emerald-300">Total: ₹{{ finalAmount().toFixed(2) }}</h3>
        <button (click)="generateBill()" class="rounded-lg bg-emerald-600 px-4 py-2 font-medium hover:bg-emerald-500">Generate Bill</button>
      </div>
    </section>

    <section class="rounded-2xl border border-slate-800 bg-slate-900/80 p-5">
      <h2 class="mb-3 text-lg font-semibold">🧾 Bill Preview / Print</h2>
      <div *ngIf="bills().length; else noBills">
        <div class="mb-3 overflow-x-auto rounded-lg border border-slate-700 p-3" *ngFor="let b of bills().slice(0,1)">
          <p class="mb-2 text-sm text-slate-300">Invoice: {{ b.invoiceNumber }} | {{ b.createdAt | date:'short' }}</p>
          <table class="w-full text-left text-sm">
            <tr class="border-b border-slate-700"><th class="p-2">Item</th><th class="p-2">Qty</th><th class="p-2">Price</th><th class="p-2">Total</th></tr>
            <tr *ngFor="let i of b.items" class="border-b border-slate-800"><td class="p-2">{{ i.productName }}</td><td class="p-2">{{ i.quantity }}</td><td class="p-2">{{ i.price }}</td><td class="p-2">{{ i.total }}</td></tr>
          </table>
          <h4 class="mt-2 font-semibold">Final: ₹{{ b.finalAmount.toFixed(2) }}</h4>
        </div>
        <button (click)="printBill()" class="rounded-lg bg-sky-600 px-4 py-2 font-medium hover:bg-sky-500">🖨️ Print</button>
      </div>
      <ng-template #noBills>No bills yet.</ng-template>
    </section>
  </div>
</div>
